name: build

on:
  push:
    tags:
      - "v*"
      - "!v*post*"  # Do not build on post-releases (pypi only)

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check guide is up to date
        run: |
          # This will fail if version numbers do not match
          make check_version_number

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install package
        run: |
          python -m pip install --upgrade pip wheel build

      - name: Build package
        run: |
          python -m build
          # Make a directory that matches the dist* glob in upload-artifact
          # in order to upload the built package in a subdirectory.
          mkdir dist_stub

      - uses: actions/upload-artifact@v3
        with:
          name: build-archives
          path: dist*


  build-win:
    runs-on: windows-latest

    # First check if doc versions match
    needs: [build-linux]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install package
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install ".[build]"

      - name: Build package
        run: |
          pyinstaller optoConfig96.spec

      - name: Compress package
        run: 7z a -tzip windows.zip ./dist/*
      - uses: actions/upload-artifact@v3
        with:
          name: build-archives
          path: windows.zip


  build-macos:
    runs-on: macos-11

    # First check if doc versions match
    needs: [build-linux]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install package and dependencies
        run: |
          brew install create-dmg
          python -m pip install --upgrade pip wheel
          python -m pip install ".[build]"

      - name: Build package
        run: |
          pyinstaller optoConfig96.spec
          chmod +x create_dmg.sh
          # Sign after removal of offending packages (see optoConfig96.spec)
          codesign -s - --force --all-architectures --timestamp --deep dist/optoConfig96.app
          ./create_dmg.sh

      - uses: actions/upload-artifact@v3
        with:
          name: build-archives
          path: darwin.dmg


  release:
    needs: [build-win, build-macos, build-linux]
    permissions:
      contents: write
    uses: ./.github/workflows/release.yaml
