name: release

on:
  workflow_call

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # Checkout for CHANGELOG
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: build-archives

      - name: Rename archives
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/*/v}
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
          mv windows.zip "windows_optoConfig96-${RELEASE_VERSION}.zip"
          mv darwin.dmg "macos_optoConfig96-${RELEASE_VERSION}.dmg"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: optoConfig96 ${{ env.RELEASE_VERSION }}
          body_path: CHANGELOG.txt
          fail_on_unmatched_files: true
          files: |
            windows_optoConfig96-*.zip
            macos_optoConfig96-*.dmg
            dist/optoConfig96-*.tar.gz
